meta_product_name: "Click & Stalk 🔎"
meta_title: "Click & Stalk - Your cyber-image under your control"
meta_description: "CHECK OUT and CLEAN UP your cyber-image before looking for your dream job."
meta_image: "card-image.png" # should exist in `app/assets/images/`
